apiVersion: v2
name: network-debug-toolbox
description: >-
  Hardened, non-root network debugging toolbox deployed as a per-node DaemonSet
  you exec into.
type: application
version: 0.1.1
appVersion: 0.1.1
keywords:
  - networking
  - debugging
  - tcpdump
  - netshoot
  - troubleshooting
home: https://github.com/jC3rny/network-debug-toolbox
sources:
  - https://github.com/jC3rny/network-debug-toolbox
maintainers:
  - name: jC3rny
